version: '3.4'
services:
  eventservice_api:
    image: eventservice
    container_name: Eventservice
    depends_on:                     
    - mongodb 
    ports:
    - 8081:80
  identity:       
    image: bizzpo/identityserver4
    environment:
    - Environment=Development
    - "Identity__Mongo__ConnectionString=mongodb://root:foobar@mongodb:27017/?readPreference=primaryPreferred&appname=identityserver"
    - Identity__Mongo__Database=Identity
    - Identity__Redis__ConnectionString=redis
    - Identity__Redis__Db=-1
    - Identity__Redis__Prefix=identity
    container_name: identity
    depends_on:            
    - redis            
    - mongodb        
    ports:
    - 5000:80        
    restart: always    
  redis:        
    image: bitnami/redis
    ports:
    - 6379:6379
    environment:            
    - ALLOW_EMPTY_PASSWORD=yes             
    restart: always   
  mongodb:
    image: mongo
    environment:            
    - MONGO_INITDB_ROOT_USERNAME=root            
    - MONGO_INITDB_ROOT_PASSWORD=foobar        
    ports:
    - 27018:27018
  spaceservice_api:
    image: space
    container_name: space
    ports:
    - 8082:80
  imageservice_api:
    image: image
    container_name: image
    ports:
    - 8083:80
  paymentservice_api:
    image: payment
    container_name: payment
    ports:
    - 8084:80
  rabbitmq:
      container_name: rabbitmq
      ports:
      - 5672:5672
      - 15672:15672
      environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password        
      image: rabbitmq:3-management    
networks:
    default:
     external: true
     name: eventidentity_net     
 