using EventService.Models.Entities;
using EventService.Models.Interfaces;
using MongoDB.Driver;

namespace EventService.Infrastructure.InterfaceImplements;

/// <summary>
/// Сервис работы с Мероприятиями посредством MongoDb
/// </summary>
public class EventMongoDbService : IBaseEventService
{
    private readonly IMongoCollection<Event> _events;
    private const string CollectionName = "events";

    /// <summary>
    /// Конструктор с начальной инициализацией Базы данных
    /// </summary>

    public EventMongoDbService(MongoClient mongo)
    {
        _events = DataBaseInitialize(mongo);

    }

    /// <summary>
    /// Метод создания мероприятия 
    /// </summary>

    public bool CreateEvent(DateTime start, DateTime end, string title, string description, Guid idimage, Guid idspace)
    {
        _events.InsertOne(new Event { Start = start, End = end, Title = title, Description = description, IdImage = idimage, IdSpace = idspace });
        return _events.Find(v => v.Title == title) != null;
    }

    /// <summary>
    /// Метод Удаления мероприятия 
    /// </summary>
    public bool DeleteEvent(Guid idevent)
    {
        return _events.Find(v => v.Id == idevent).FirstOrDefault() != null && _events.DeleteOne(v => v.Id == idevent).IsAcknowledged;
    }

    /// <summary>
    /// Метод получения всех мероприятий
    /// </summary>

    public List<Event> GetAllEvents()
    {
        return _events.Find(v => true).ToList();
    }

    /// <summary>
    /// Метод получения всех мероприятий на неделю
    /// </summary>

    public List<Event> GetAllEventsForTheWeek()
    {
        var start = DateTime.UtcNow;

        var end = start.AddDays(7);

        return _events.Find(v => v.Start > start || v.End <= end).ToList();
    }

    /// <summary>
    ///Метод заполения бесплатных билетов на определённое мероприятие
    /// </summary>

    public bool SetFreeTickets(int count, Guid idevent, bool isautogeneratedplaces)
    {
        var ticketList = new List<Ticket>();
        if (_events.Find(v => v.Id == idevent).FirstOrDefault() == null) return false;

        // ReSharper disable once SuggestVarOrType_BuiltInTypes
        for (int i = 1; i <= count; i++) ticketList.Add(new Ticket { Seat = isautogeneratedplaces ? i : null });

        var update = Builders<Event>.Update.Set(v => v.Tickets, ticketList);

        return _events.UpdateOne(v => v.Id == idevent, update).IsAcknowledged;
    }

    /// <summary>
    /// Метод выдачи билета на мероприятие
    /// </summary>

    public Ticket IssueTicket(Guid idevent, Guid idowner)
    {
        var eventDefault = _events.Find(v => v.Id == idevent).FirstOrDefault();
        if (eventDefault is not { IsTicketsAvailable: true }) return null!;
        {
            var desireTicket = eventDefault.Tickets.FirstOrDefault();
            if (desireTicket == null) return null!;
            desireTicket.IdOwner = idowner;
            var update = Builders<Event>.Update.Set(v => v.Tickets, eventDefault.Tickets);
            _events.UpdateOne(v => eventDefault.Id == v.Id, update);
            return desireTicket;
        }

    }

    /// <summary>
    /// Метод проверки наличия билета у пользователя на мероприятие
    /// </summary>

    public bool HaveATicket(Guid idevent, Guid idowner)
    {
        var eventDefault = _events.Find(v => v.Id == idevent).FirstOrDefault();
        return eventDefault != null && eventDefault.Tickets.Any(v => v.IdOwner == idowner);
    }

    /// <summary>
    /// Метод обновления мероприятия
    /// </summary>

    public bool UpdateEvent(Guid idevent, DateTime? start, DateTime? end, string? title, string? description, Guid? idimage, Guid? idspace)
    {
        var uploadingEvent = _events.Find(v => v.Id == idevent).FirstOrDefault();

        if (uploadingEvent == null) return false;
        {
            var update = Builders<Event>.Update;
            var updateDefinitions = new List<UpdateDefinition<Event>>();
            if (start != null && start != uploadingEvent.Start) updateDefinitions.Add(update.Set(v => v.Start, start));
            if (end != null && end != uploadingEvent.End) updateDefinitions.Add(update.Set(v => v.End, end));
            if (!string.IsNullOrEmpty(title) && title != uploadingEvent.Title) updateDefinitions.Add(update.Set(v => v.Title, title));
            if (!string.IsNullOrEmpty(description) && description != uploadingEvent.Description) updateDefinitions.Add(update.Set(v => v.Description, description));
            if (idimage != default(Guid)) updateDefinitions.Add(update.Set(v => v.IdImage, idimage));
            if (idspace != default(Guid)) updateDefinitions.Add(update.Set(v => v.IdSpace, idspace));
            var finalUpdate = update.Combine(updateDefinitions);
            return _events.UpdateOne(v => uploadingEvent.Id == v.Id, finalUpdate).IsAcknowledged;
        }

    }

    // ReSharper disable once MemberCanBeMadeStatic.Local решарпер предлагает сделать метод статичным, но в этом нет никакого смысла
    // ReSharper disable once SuggestBaseTypeForParameter
    private IMongoCollection<Event> DataBaseInitialize(MongoClient client)
    {
        // ReSharper disable once StringLiteralTypo
        var database = client.GetDatabase("eventdb");

        var collection = database.GetCollection<Event>(CollectionName);

        if (database.ListCollections().FirstOrDefault() != null) return collection;
        database.CreateCollection(CollectionName);
        collection.InsertOne(new Event { Id = Guid.Parse("00000000-0000-0000-0000-000000000000"), Description = "TestDescription", Start = DateTime.UtcNow, End = DateTime.UtcNow.AddDays(1), Title = "TestTitle", IdImage = Guid.Parse("7febf16f-651b-43b0-a5e3-0da8da49e90d"), IdSpace = Guid.Parse("7febf16f-651b-43b0-a5e3-0da8da49e90d") });

        return collection;
    }

    /// <summary>
    /// Метод проверки наличия места у билета
    /// </summary>

    public int? CheckSeat(Guid idevent, Guid idticket)
    {
        return _events.Find(v => v.Id == idevent).FirstOrDefault().Tickets.FirstOrDefault(v => v.Id == idticket)?.Seat;
    }
}